### ISSUE TITLE
DHT22 MQTT

### ISSUE THREAD

**Issue by outrun0506** [mertenats/Open-Home-Automation#9]
Hi,

i flashed your Sketch, and it seems to work.

After my setup in Home Assistant, humidity keeps saying unknow.

Heres the Output from the IDE-Serial Monitor:

```
.........
INFO: WiFi connected
INFO: IP address: 
192.168.0.59
INFO: Attempting MQTT connection...INFO: connected
{
  "temperature": "22.80",
  "humidity": "34.10"
}
INFO: Closing the MQTT connection
INFO: Closing the Wifi connection
```

Temperature works fine.

Thanks for help

BR

Lukas

**Comment by mertenats** [comment]
Hi Lukas,
Thank you for your message. The output is correct and the MQTT message is received by Home Assistant (it works for the temperature). There is probably a problem when HA tries to extract the humidity from the payload of the MQTT message. I can not test anything now, but you should find some help at the bottom of this [page](https://home-assistant.io/components/mqtt/).

Are you using the same topic for the humidity sensor?

```yaml
sensor 1:
  platform: mqtt
  state_topic: 'office/sensor1'
  name: 'Temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'

sensor 2:
  platform: mqtt
  state_topic: 'office/sensor1'
  name: 'Humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'
```

Best regards,
Sam
